### ISSUE TITLE
Service fails to activate on RTC 5.0.2

### ISSUE THREAD

**Issue by innerjoin** [jazz-community/rtc-workitem-bulk-mover-service#11]
*Steps to reproduce:*
-  Download the package _Jazz Team Server and the CCM Application, and Trial licenses for Rational Team Concert_ for RTC 5.0.2 on [Jazz.net](https://jazz.net/downloads/rational-team-concert/releases/5.0.2?p=allDownloads). 
- Extract server and Install plug-ins (Menu Provider, Mover UI, Mover Service)
- Go through the server setup
- The new Menu entry plus the mover UI should be available:
- Open browser console and you and you should see the following console error:
> https://localhost:9443/ccm/service/com.siemens.bt.jazz.services.WorkItemBulkMover.IWorkItemBulkMoverService/project-areas 
> Failed to load resource: the server responded with a status of 404 (Not Found)
- Go to `/ccm/service`. The Bulk Mover Service is missing
- Open the `CCM.log`. The following error can be found:
```
2018-01-18 16:26:32,974 [          http-bio-9443-exec-5] ERROR tory.common.transport.services.TeamServiceRegistry  - CRJAZ1143I Die OSGi-Services für den Deskriptor konnten nicht registriert werden: ServiceProviderElementDescriptor@2b252b25, implementationClass="com.siemens.bt.jazz.services.WorkItemBulkMover.WorkItemBulkMoverService", bundle="com.siemens.bt.jazz.services.WorkItemBulkMover", componentId="com.siemens.bt.jazz.services.WorkItemBulkMover", startPolicy=<EARLY>.
java.lang.UnsupportedClassVersionError: JVMCFRE003 Ungültige übergeordnete Version; Klasse=com/siemens/bt/jazz/services/base/BaseService, Offset=6
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:287)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.defineClass(DefaultClassLoader.java:188)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.defineClass(ClasspathManager.java:580)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findClassImpl(ClasspathManager.java:550)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClassImpl(ClasspathManager.java:481)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass_LockClassName(ClasspathManager.java:460)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:447)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:393)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:469)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:410)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:643)
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:287)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.defineClass(DefaultClassLoader.java:188)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.defineClass(ClasspathManager.java:580)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findClassImpl(ClasspathManager.java:550)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClassImpl(ClasspathManager.java:481)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass_LockClassName(ClasspathManager.java:460)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:447)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:393)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:469)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:410)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:643)
	at org.eclipse.osgi.internal.loader.BundleLoader.loadClass(BundleLoader.java:338)
	at org.eclipse.osgi.framework.internal.core.BundleHost.loadClass(BundleHost.java:232)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.loadClass(AbstractBundle.java:1197)
	at com.ibm.team.repository.common.transport.AbstractElementDescriptor.basicLoadClass(AbstractElementDescriptor.java:78)
	at com.ibm.team.repository.common.transport.AbstractElementDescriptor.loadClass(AbstractElementDescriptor.java:515)
	at com.ibm.team.repository.common.transport.internal.registry.ServiceProviderElementDescriptor.getImplementationClass(ServiceProviderElementDescriptor.java:153)
	at com.ibm.team.repository.common.transport.internal.registry.OsgiServicesManager.register(OsgiServicesManager.java:408)
	at com.ibm.team.repository.common.transport.services.TeamServiceRegistry.registerServices(TeamServiceRegistry.java:329)
	at com.ibm.team.repository.common.transport.services.TeamServiceRegistry.initialize(TeamServiceRegistry.java:290)
	at com.ibm.team.repository.common.transport.services.TeamServiceRegistry.start(TeamServiceRegistry.java:371)
	at com.ibm.team.repository.common.transport.services.TeamServiceRegistry.getService(TeamServiceRegistry.java:224)
	at com.ibm.team.repository.service.internal.LogFeedAppender.<init>(LogFeedAppender.java:97)
	at com.ibm.team.repository.service.internal.LogFeedAppender.getInstance(LogFeedAppender.java:105)
	at com.ibm.team.repository.servlet.internal.TeamLogger.init(TeamLogger.java:30)
	at com.ibm.team.repository.servlet.AbstractTeamServerServlet.init(AbstractTeamServerServlet.java:1470)
	at com.ibm.team.repository.servlet.TeamServerServlet.init(TeamServerServlet.java:209)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.initializeDelegate(ServletManager.java:195)
	at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:179)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:126)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:76)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.eclipse.equinox.servletbridge.BridgeServlet.service(BridgeServlet.java:120)
	at com.ibm.team.repository.server.servletbridge.JazzServlet.service(JazzServlet.java:74)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.ibm.team.repository.server.servletbridge.BridgeFilter.initialize(BridgeFilter.java:303)
	at com.ibm.team.repository.server.servletbridge.BridgeFilter.doFilter(BridgeFilter.java:196)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:312)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:761)
```

**Comment by innerjoin** [comment]
@SBI- any update from your side on this?

**Comment by innerjoin** [comment]
To any reader who follows this work item: we are currently unable to invest in compatibility for older releases. We therefore highly recommend to upgrade to one of the latest RTC releases
